name: Update EPG

on:
  schedule:
    - cron: "0 20 * * *"   # jalan tiap jam 3 pagi WIB
  workflow_dispatch:        # bisa dijalankan manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install requests lxml

      - name: Grab & Merge EPG
        run: python epg-auto/grab_epg.py

      - name: Commit & Push epgtv.xml
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add epgtv.xml
          git commit -m "Update EPG" || echo "No changes"
          git push
